# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='公司名称')),
                ('contactsusr', models.CharField(max_length=10, verbose_name='联系人')),
                ('phonenumber', models.IntegerField(verbose_name='联系人手机号')),
                ('projectname', models.CharField(max_length=20, verbose_name='项目名')),
                ('account', models.CharField(max_length=30, verbose_name='登陆账号')),
                ('password', models.CharField(max_length=30, verbose_name='登陆密码')),
                ('balance', models.FloatField(max_length=10, verbose_name='账户余额')),
            ],
            options={
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='Csp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='云服务商名称')),
                ('remark', models.CharField(max_length=50, verbose_name='备注')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '云服务商',
                'verbose_name_plural': '云服务商',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='组名称')),
                ('remark', models.CharField(max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '公司组',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=20, verbose_name='服务器角色')),
                ('usage', models.CharField(max_length=20, verbose_name='服务器用途')),
                ('pub_ipaddress', models.GenericIPAddressField(verbose_name='公网地址')),
                ('private_ipaddress', models.GenericIPAddressField(verbose_name='私网地址')),
                ('customer', models.FloatField(max_length=10, verbose_name='月费用')),
                ('password', models.CharField(max_length=30, verbose_name='服务器密码')),
                ('cpu', models.IntegerField(verbose_name='CPU核数')),
                ('mem', models.IntegerField(verbose_name='内存大小')),
                ('bandwidth', models.IntegerField(verbose_name='带宽')),
                ('port', models.IntegerField(verbose_name='远程端口')),
                ('area', models.CharField(max_length=10, verbose_name='地区')),
                ('expiration_time', models.DateField(verbose_name='到期时间')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Company')),
            ],
            options={
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='Cspname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Csp'),
        ),
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Group'),
        ),
    ]
