# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-15 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': '项目组'},
        ),
    ]
